package massim.ankamas;
import eis.iilang.Percept;
import eis.iilang.Action;
import eis.iilang.Identifier;
import java.util.List;
import eis.exceptions.ActException;
import org.apache.logging.log4j.Logger;
import massim.ankamas.TPercept;
import massim.ankamas.agents.BasicAgent
import eis.iilang.Numeral;

global Logger logger;
global massim.eismassim.EnvironmentInterface eis;
global BasicAgent agent;

rule "If simulation starts for the first time"
when
    TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().toString().equals("[]"))
    or TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().get(0).toString().equals("request"))
    or TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().get(0).toString().equals("adopt"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "If simulation starts for the first time : move randomly : " + direction);
end

rule "When previous move is successful"
when
    $tprcpt : TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().toString().equals("[move]"))
    $lstactnrslt : TPercept(prcptid == $tprcpt.prcptid, prcpt.getName().equals("lastActionResult"), prcpt.getParameters().toString().equals("[success]"))
    $lstactnprms : TPercept(prcptid == $tprcpt.prcptid, prcpt.getName().equals("lastActionParams"), $direction : prcpt.getParameters().toString())
then
    eis.performAction("A1", new Action("move", new Identifier($direction.substring(2,3))));
    logger.info("$$$$$ RULE EXECUTION : " + "When previous move is successful : move randomly : " + $direction.substring(2,3));
end

rule "If there is an obstacle in front of the agentA1 after a move"
when
    $tprcpt : TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().toString().equals("[move]"))
    $lstactnrslt : TPercept(prcptid == $tprcpt.prcptid, prcpt.getName().equals("lastActionResult"), prcpt.getParameters().toString().equals("[failed_path]"))
    $lstactnprms : TPercept(prcptid == $tprcpt.prcptid, prcpt.getName().equals("lastActionParams"), $direction : prcpt.getParameters().toString())
then
    if($direction.equals("[[n]]"))
        eis.performAction("A1", new Action("clear",new Numeral(0), new Numeral(-1) ));
    else if ($direction.equals("[[s]]"))
        eis.performAction("A1", new Action("clear",new Numeral(0), new Numeral(1) ));
    else if ($direction.equals("[[e]]"))
        eis.performAction("A1", new Action("clear",new Numeral(1), new Numeral(0) ));
     else
        eis.performAction("A1", new Action("clear",new Numeral(-1), new Numeral(0) ));
    logger.info("$$$$$ RULE EXECUTION : " + "If there is an obstacle in front of the agent : clear " + $direction);
end

rule "If the obstacle in front of the agentA1 is successfully cleared"
when
    $tprcpt : TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().toString().equals("[clear]"))
    $lstactnrslt : TPercept(prcptid == $tprcpt.prcptid, prcpt.getName().equals("lastActionResult"), prcpt.getParameters().toString().equals("[success]"))
    $lstactnprms : TPercept(prcptid == $tprcpt.prcptid, prcpt.getName().equals("lastActionParams"), $direction : prcpt.getParameters().toString())
then
    if($direction.equals("[[0,-1]]"))
        eis.performAction("A1", new Action("move", new Identifier("n")));
    else if ($direction.equals("[[0,1]]"))
        eis.performAction("A1", new Action("move", new Identifier("s")));
    else if ($direction.equals("[[1,0]]"))
        eis.performAction("A1", new Action("move", new Identifier("e")));
    else
        eis.performAction("A1", new Action("move", new Identifier("w")));
    logger.info("$$$$$ RULE EXECUTION : " + "If the obstacle in front of the agentA1 is successfully cleared : move to the same direction " + $direction);
end

rule "If massim produces failed_random randomly"
when
    $lstactnrslt : TPercept(prcpt.getName().equals("lastActionResult"), prcpt.getParameters().toString().equals("[failed_random]"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "If massim produces failed_random randomly : move randomly : " + direction);
end

rule "If massim produces failed_status after a move"
when
    $tprcpt : TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().toString().equals("[move]"))
    $lstactnrslt : TPercept(prcptid == $tprcpt.prcptid, prcpt.getName().equals("lastActionResult"), prcpt.getParameters().toString().equals("[failed_status]"))
then
    String direction = agent.generateRandomDirection();
    eis.performAction("A1", new Action("move", new Identifier(direction)));
    logger.info("$$$$$ RULE EXECUTION : " + "failed_status : move randomly : " + direction);
end

rule "If the agent is in role zone"
when
    TPercept(prcpt.getName().equals("roleZone"), prcpt.getParameters().get(0).toString().equals("0")
                                                        && prcpt.getParameters().get(1).toString().equals("0"))
    not TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().get(0).toString().equals("adopt"))
then
    eis.performAction("A1", new Action("adopt", new Identifier("constructor")));
    logger.info("$$$$$ RULE EXECUTION : If the agent is in role zone: Adopt role");
end

rule "If there is a dispenser at east"
when
    TPercept(prcpt.getName().equals("thing"), prcpt.getParameters().get(2).toString().equals("dispenser")
                                                        && prcpt.getParameters().get(0).toString().equals("1")
                                                        && prcpt.getParameters().get(1).toString().equals("0"))
    not TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().get(0).toString().equals("request"))
    not TPercept(prcpt.getName().equals("lastActionResult"), prcpt.getParameters().get(0).toString().equals("failed_role"))
then
    eis.performAction("A1", new Action("request", new Identifier("e")));
    logger.info("$$$$$ RULE EXECUTION : If there is a dispenser at east of the agent : Block requested from east");
end

rule "If there is a dispenser at west"
when
    TPercept(prcpt.getName().equals("thing"), prcpt.getParameters().get(2).toString().equals("dispenser")
                                                        && prcpt.getParameters().get(0).toString().equals("-1")
                                                        && prcpt.getParameters().get(1).toString().equals("0"))
    not TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().get(0).toString().equals("request"))
    not TPercept(prcpt.getName().equals("lastActionResult"), prcpt.getParameters().get(0).toString().equals("failed_role"))
then
    eis.performAction("A1", new Action("request", new Identifier("w")));
    logger.info("$$$$$ RULE EXECUTION : If there is a dispenser at west of the agent : Block requested from west");
end

rule "If there is a dispenser at south"
when
    TPercept(prcpt.getName().equals("thing"), prcpt.getParameters().get(2).toString().equals("dispenser")
                                                        && prcpt.getParameters().get(0).toString().equals("0")
                                                        && prcpt.getParameters().get(1).toString().equals("1"))
    not TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().get(0).toString().equals("request"))
    not TPercept(prcpt.getName().equals("lastActionResult"), prcpt.getParameters().get(0).toString().equals("failed_role"))
then
    eis.performAction("A1", new Action("request", new Identifier("s")));
    logger.info("$$$$$ RULE EXECUTION : If there is a dispenser at south of the agent : Block requested from south");
end

rule "If there is a dispenser at north"
when
    TPercept(prcpt.getName().equals("thing"), prcpt.getParameters().get(2).toString().equals("dispenser")
                                                        && prcpt.getParameters().get(0).toString().equals("0")
                                                        && prcpt.getParameters().get(1).toString().equals("-1"))
    not TPercept(prcpt.getName().equals("lastAction"), prcpt.getParameters().get(0).toString().equals("request"))
    not TPercept(prcpt.getName().equals("lastActionResult"), prcpt.getParameters().get(0).toString().equals("failed_role"))
then
    eis.performAction("A1", new Action("request", new Identifier("n")));
    logger.info("$$$$$ RULE EXECUTION : If there is a dispenser at north of the agent : Block requested from north");
end